formatVersion: 1
formatType: am-configuration
---
# basic AM functionality - the builtin apps are in 'apps'.

applications:
  builtinAppsManifestDir: "apps"

# QML apps will be able to import from modules...

runtimes:
  qml:
    importPaths: [ "modules" ]

# ... as well as the SystemUI

ui:
  fullscreen: yes
  mainQml: "Main1280x800.qml"
  importPaths: [ "modules" ]
  additionalConfiguration:
    appStoreServerUrl: 'http://beachhead.pelagicore.de:8080'
  windowIcon: "modules/assets/icons/active/apps@96.png"

# development setup: no security

flags:
  noSecurity: yes
  noUiWatchdog: yes

