formatVersion: 1
formatType: am-configuration
---
# basic AM functionality - the builtin apps are in 'apps'.

applications:
  builtinAppsManifestDir: "${CONFIG_PWD}/apps"

# QML apps will be able to import from modules...

runtimes:
  qml:
    importPaths: [ "${CONFIG_PWD}/imports/shared" ]

# ... as well as the SystemUI

ui:
  fullscreen: yes
  mainQml: "${CONFIG_PWD}/Main.qml"
  importPaths: [ "${CONFIG_PWD}/imports/shared", "${CONFIG_PWD}/imports/system" ]
  windowIcon: "${CONFIG_PWD}/imports/shared/assets/icons/active/apps@96.png"

systemProperties:
    public:
      styleConfig: "Config1920x1080.qml"
      showCluster: yes
    private:
      appStoreServerUrl: 'http://chaos.pelagicore.net:8080'

# development setup: no security

flags:
  noSecurity: yes
  noUiWatchdog: yes

